const productos = [
  {
    id: 0,
    title: "CINTA MICROPORE",
    description: "Cinta adhesiva hipoalergénica de papel, sin látex.",
    brand: "3M",
    variant: "1530-0",
    subdesc: "Blanca de 1,25cm x 9,14m",
    unit: "Cajon x 10 cajas x 24 rollos",
    price: 115.63,
  },
  {
    id: 0,
    title: "CINTA MICROPORE",
    description: "Cinta adhesiva hipoalergénica de papel, sin látex.",
    brand: "3M",
    variant: "1530-1",
    subdesc: "Blanca de 2,5cm x 9,14m",
    unit: "Cajon x 10 cajas x 12 rollos",
    price: 73.5,
  },
  {
    id: 0,
    title: "CINTA MICROPORE",
    description: "Cinta adhesiva hipoalergénica de papel, sin látex.",
    brand: "3M",
    variant: "1530-2",
    subdesc: "Blanca de 5cm x 9,14m",
    unit: "Cajon x 10 cajas x 6 rollos",
    price: 78.17,
  },
  {
    id: 0,
    title: "CINTA MICROPORE",
    description: "Cinta adhesiva hipoalergénica de papel, sin látex.",
    brand: "3M",
    variant: "1533-1",
    subdesc: "Piel de 2,5cm x 9,14m",
    unit: "Cajon x 10 cajas x 12 rollos",
    price: 280.77,
  },
  {
    id: 1,
    title: "CINTA TRANSPORE",
    description:
      "Cinta adhesiva hipoalergenica de plástico transparente, sin látex.",
    brand: "3M",
    variant: "1527-0",
    subdesc: "Transparente de 1,25cm x 9,14m",
    unit: "Cajon x 10 cajas x 24 rollos",
    price: 98.71,
  },
  {
    id: 1,
    title: "CINTA TRANSPORE",
    description:
      "Cinta adhesiva hipoalergenica de plástico transparente, sin látex.",
    brand: "3M",
    variant: "1527-1",
    subdesc: "Transparente de 2,5cm x 9,14m",
    unit: "Cajon x 10 cajas x 12 rollos",
    price: 99.59,
  },
  {
    id: 1,
    title: "CINTA TRANSPORE",
    description:
      "Cinta adhesiva hipoalergenica de plástico transparente, sin látex.",
    brand: "3M",
    variant: "1527-2",
    subdesc: "Transparente de 5cm x 9,14m",
    unit: "Cajon x 10 cajas x 6 rollos",
    price: 103.16,
  },
  {
    id: 2,
    title: "CINTA DURAPORE",
    description: "Cinta adhesiva hipoalergenica de seda, sin látex.",
    brand: "3M",
    variant: "1538-1",
    subdesc: "Blanca de 2,5cm x 9,14m",
    unit: "Caja x 12 rollos",
    price: 26.85,
  },
  {
    id: 2,
    title: "CINTA DURAPORE",
    description: "Cinta adhesiva hipoalergenica de seda, sin látex.",
    brand: "3M",
    variant: "1538-2",
    subdesc: "Blanco de 5cm x 9,14m",
    unit: "Caja x 6 rollos",
    price: 19.09,
  },
  {
    id: 3,
    title: "CINTA TRANSPORE WHITE",
    description: "Cinta adhesiva hipoalergenica de papel perforado, sin látex.",
    brand: "3M",
    variant: "1534-1",
    subdesc: "Blanca de 2,5cm x 9,14m",
    unit: "Cajon x 10 cajas x 12 rollos",
    price: 203.83,
  },
  {
    id: 3,
    title: "CINTA TRANSPORE WHITE",
    description: "Cinta adhesiva hipoalergenica de papel perforado, sin látex.",
    brand: "3M",
    variant: "1534-2",
    subdesc: "Blanca de 5cm x 9,14m",
    unit: "Cajon x 10 cajas x 6 rollos",
    price: 172.67,
  },
  {
    id: 4,
    title: "CINTA MEDIPORE H",
    description:
      "Cinta adhesiva hipoalergenica de poliéster no tejido, sin látex.",
    brand: "3M",
    variant: "2861",
    subdesc: "Blanca de 2,5cm x 9,14m",
    unit: "Caja x 24 rollos",
    price: 60.22,
  },
  {
    id: 4,
    title: "CINTA MEDIPORE H",
    description:
      "Cinta adhesiva hipoalergenica de poliéster no tejido, sin látex.",
    brand: "3M",
    variant: "2862",
    subdesc: "Blanca de 5cm x 9,14m",
    unit: "Caja x 12 rollos",
    price: 62.55,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1622W",
    subdesc: "4,4cm x 4,4cm",
    unit: "Caja x 100",
    price: 26.38,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1624W",
    subdesc: "6cm x 7cm",
    unit: "Caja x 100",
    price: 28.79,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1626W",
    subdesc: "10cm x 12cm",
    unit: "Caja x 50",
    price: 34.19,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1627",
    subdesc: "10cm x 25cm",
    unit: "Caja x 20",
    price: 80.22,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1628",
    subdesc: "15cm x 20cm",
    unit: "Caja x 10",
    price: 56.73,
  },
  {
    id: 5,
    title: "APÓSITO TRANSPARENTE",
    description:
      "La película Tegaderm™ consiste en un respaldo de película delgada con un adhesivo hipoalergénico sin látex para el cuidado de la piel y la fijación de vías intravenosas de forma segura.",
    brand: "3M",
    variant: "1629",
    subdesc: "20cm x 30cm",
    unit: "Caja x 10",
    price: 60.05,
  },
  {
    id: 6,
    title: "APÓSITO IV",
    description:
      "Diseñados para proporcionar un aseguramiento avanzado del catéter, visualización continua del sitio de inserción y excelente manejo de la humedad.",
    brand: "3M",
    variant: "1685",
    subdesc: "8,5cm x 11,5cm",
    unit: "Caja x 50",
    price: 125.12,
  },
  {
    id: 6,
    title: "APÓSITO IV",
    description:
      "Diseñados para proporcionar un aseguramiento avanzado del catéter, visualización continua del sitio de inserción y excelente manejo de la humedad.",
    brand: "3M",
    variant: "1683",
    subdesc: "6,5cm x 7cm",
    unit: "Caja x 100",
    price: 121.33,
  },
  {
    id: 6,
    title: "APÓSITO IV",
    description:
      "Diseñados para proporcionar un aseguramiento avanzado del catéter, visualización continua del sitio de inserción y excelente manejo de la humedad.",
    brand: "3M",
    variant: "1682",
    subdesc: "5,08cm x 7cm",
    unit: "Caja x 100",
    price: 125.55,
  },
  {
    id: 6,
    title: "APÓSITO IV",
    description:
      "Diseñados para proporcionar un aseguramiento avanzado del catéter, visualización continua del sitio de inserción y excelente manejo de la humedad.",
    brand: "3M",
    variant: "1680",
    subdesc: "3,8cm x 4,4cm",
    unit: "Caja x 100",
    price: 133.57,
  },
  {
    id: 7,
    title: "APÓSITO CHG",
    description:
      "Apósito con gluconato de clorhexidina para reducir las infecciones sanguineas relacionadas con el uso de catéteres y la colonización del catéter vascular.",
    brand: "3M",
    variant: "1657R",
    subdesc: "8,50cm x 11,50cm",
    unit: "Caja x 25",
    price: 221.15,
  },
  {
    id: 7,
    title: "APÓSITO CHG",
    description:
      "Apósito con gluconato de clorhexidina para reducir las infecciones sanguineas relacionadas con el uso de catéteres y la colonización del catéter vascular.",
    brand: "3M",
    variant: "1660R",
    subdesc: "7cm x 8,50cm",
    unit: "Caja x 25",
    price: 196.3,
  },
  {
    id: 8,
    title: "APÓSITO + PAD",
    description:
      "Apósito transparente estéril con almohadilla absorbente no adherente, ideal para cubrir heridas post-quirúrgicas y quemaduras.",
    brand: "3M",
    variant: "3582",
    subdesc: "5cm x 7cm",
    unit: "Caja x 50",
    price: 52.17,
  },
  {
    id: 8,
    title: "APÓSITO + PAD",
    description:
      "Apósito transparente estéril con almohadilla absorbente no adherente, ideal para cubrir heridas post-quirúrgicas y quemaduras.",
    brand: "3M",
    variant: "3590",
    subdesc: "9cm x 20cm",
    unit: "Caja x 25",
    price: 120.65,
  },
  {
    id: 8,
    title: "APÓSITO + PAD",
    description:
      "Apósito transparente estéril con almohadilla absorbente no adherente, ideal para cubrir heridas post-quirúrgicas y quemaduras.",
    brand: "3M",
    variant: "3591",
    subdesc: "9cm x 25cm",
    unit: "Caja x 25",
    price: 93.05,
  },
  {
    id: 8,
    title: "APÓSITO + PAD",
    description:
      "Apósito transparente estéril con almohadilla absorbente no adherente, ideal para cubrir heridas post-quirúrgicas y quemaduras.",
    brand: "3M",
    variant: "3593",
    subdesc: "9cm x 35cm",
    unit: "Caja x 25",
    price: 200.88,
  },
  {
    id: 9,
    title: "ELECTRODO DE FUERTE ADHESIÓN",
    description:
      "Electrodo de soporte de espuma con fuerte adhesión inicial, para aplicaciones de corta y larga duración. Con broche de cloruro de plata.",
    brand: "3M",
    variant: "2228",
    subdesc: "Caja x 20 bolsas x 50 unidades",
    unit: "Caja x 20 bolsas x 50 unidades",
    price: 86.56,
  },
  {
    id: 10,
    title: "ELECTRODO DE SOPORTE DE ESPUMA",
    description:
      "Electrodo de soporte de espuma radiopaco, ideal para monitorizaciones de larga duración, con broche de carbono apto para resonancia magnética y hemodinamia.",
    brand: "3M",
    variant: "2228",
    subdesc: "Caja x 20 bolsas x 50 unidades",
    unit: "Caja x 20 bolsas x 50 unidades",
    price: 86.56,
  },
  {
    id: 11,
    title: "ELECTRODO PEDIÁTRICO",
    description:
      "Electrodo pediátrico de soporte de cinta suave, reposicionable.",
    brand: "3M",
    variant: "2268-3",
    subdesc: "Caja x 200 bolsas x 3 unidades",
    unit: "Caja x 200 bolsas x 3 unidades",
    price: 242.73,
  },
  {
    id: 12,
    title: "CORTADORA DE VELLO CLIPPER",
    description:
      "Cortadora de vello Clipper para todo tipo de procedimiento. Cuchilla descartable.",
    brand: "3M",
    variant: "9680",
    subdesc: "Cuchilla descartable",
    unit: "Caja x 50",
    price: 344.96,
  },
  {
    id: 12,
    title: "CORTADORA DE VELLO CLIPPER",
    description:
      "Cortadora de vello Clipper para todo tipo de procedimiento. Cuchilla descartable.",
    brand: "3M",
    variant: "9686",
    subdesc: "Cargador de máquina",
    unit: "Unidad",
    price: 35.88,
  },
  {
    id: 12,
    title: "CORTADORA DE VELLO CLIPPER",
    description:
      "Cortadora de vello Clipper para todo tipo de procedimiento. Cuchilla descartable.",
    brand: "3M",
    variant: "9681",
    subdesc: "Máquina cortadora",
    unit: "Unidad",
    price: 20.85,
  },
  {
    id: 13,
    title: "PELÍCULA PROTECTORA CAVILON",
    description:
      "La película barrera no irritante 3M™ Cavilon™ es la película barrera líquida original sin alcohol que seca rápidamente para formar un revestimiento transparente y transpirable sobre la piel.",
    brand: "3M",
    variant: "3346E",
    subdesc: "Cavilon spray",
    unit: "Caja x 12",
    price: 128.85,
  },
  {
    id: 13,
    title: "PELÍCULA PROTECTORA CAVILON",
    description:
      "La película barrera no irritante 3M™ Cavilon™ es la película barrera líquida original sin alcohol que seca rápidamente para formar un revestimiento transparente y transpirable sobre la piel.",
    brand: "3M",
    variant: "3345E",
    subdesc: "Cavilon hisopo x 3ml",
    unit: "Caja x 25",
    price: 95.36,
  },
  {
    id: 13,
    title: "PELÍCULA PROTECTORA CAVILON",
    description:
      "La película barrera no irritante 3M™ Cavilon™ es la película barrera líquida original sin alcohol que seca rápidamente para formar un revestimiento transparente y transpirable sobre la piel.",
    brand: "3M",
    variant: "3343",
    subdesc: "Cavilon hisopo x 1ml",
    unit: "Caja x 25",
    price: 72.33,
  },
  {
    id: 13,
    title: "PELÍCULA PROTECTORA CAVILON",
    description:
      "La película barrera no irritante 3M™ Cavilon™ es la película barrera líquida original sin alcohol que seca rápidamente para formar un revestimiento transparente y transpirable sobre la piel.",
    brand: "3M",
    variant: "3391",
    subdesc: "Cavilon crema x 28gr",
    unit: "Caja x 12",
    price: null,
  },
  {
    id: 13,
    title: "PELÍCULA PROTECTORA CAVILON",
    description:
      "La película barrera no irritante 3M™ Cavilon™ es la película barrera líquida original sin alcohol que seca rápidamente para formar un revestimiento transparente y transpirable sobre la piel.",
    brand: "3M",
    variant: "3392",
    subdesc: "Cavilon crema x 92gr",
    unit: "Caja x 12",
    price: null,
  },
  {
    id: 14,
    title: "PLACA PARA ELECTROBISTURI",
    description:
      "Placa electroquirúrgica universal para usar con electrobisturí. Compatible con sistema REM, Valleylab. Apto para adultos y pediátricos.",
    brand: "3M",
    variant: "9160F",
    subdesc: "Caja x 200",
    unit: "Caja x 200",
    price: 373.15,
  },
  {
    id: 14,
    title: "PLACA PARA ELECTROBISTURI",
    description:
      "Placa electroquirúrgica universal para usar con electrobisturí. Compatible con sistema REM, Valleylab. Apto para adultos y pediátricos.",
    brand: "3M",
    variant: "21174",
    subdesc: "Unidad",
    unit: "Unidad",
    price: 276.61,
  },
  {
    id: 15,
    title: "CAMPOS QUIRÚRGICOS DE INCISIÓN",
    description:
      "Campo quirúrgico con iodo para crear una superficie libre de microorganismos sobre la piel del paciente.",
    brand: "3M",
    variant: "Ioban 6640",
    subdesc: "35cm x 35cm",
    unit: "Caja x 10",
    price: 117.67,
  },
  {
    id: 15,
    title: "CAMPOS QUIRÚRGICOS DE INCISIÓN",
    description:
      "Campo quirúrgico con iodo para crear una superficie libre de microorganismos sobre la piel del paciente.",
    brand: "3M",
    variant: "Ioban 6650",
    subdesc: "60cm x 45cm",
    unit: "Caja x 10",
    price: 101.28,
  },
  {
    id: 15,
    title: "CAMPOS QUIRÚRGICOS DE INCISIÓN",
    description:
      "Campo quirúrgico con iodo para crear una superficie libre de microorganismos sobre la piel del paciente.",
    brand: "3M",
    variant: "Ioban 6651",
    subdesc: "60cm x 85cm",
    unit: "Caja x 10",
    price: 193.32,
  },
  {
    id: 16,
    title: "CAMPOS QUIRÚRGICOS DE INCISIÓN",
    description:
      "Campo quirúrgico sin iodo para generar una barrera de aislamiento y estéril.",
    brand: "3M",
    variant: "Steri Drape 1040",
    subdesc: "35cm x 35cm",
    unit: "Caja x 10",
    price: 59.87,
  },
  {
    id: 16,
    title: "CAMPOS QUIRÚRGICOS DE INCISIÓN",
    description:
      "Campo quirúrgico sin iodo para generar una barrera de aislamiento y estéril.",
    brand: "3M",
    variant: "Steri Drape 1050",
    subdesc: "60cm x 45cm",
    unit: "Caja x 10",
    price: 67.44,
  },
  {
    id: 17,
    title: "CAMPOS QUIRÚRGICOS STERI DRAPE",
    description:
      "Campos quirúrgicos estériles para procedimientos médicos y quirúrgicos.",
    brand: "3M",
    variant: "1015",
    subdesc: "120cm x 130cm",
    unit: "Caja x 10",
    price: 111.62,
  },
  {
    id: 17,
    title: "CAMPOS QUIRÚRGICOS STERI DRAPE",
    description:
      "Campos quirúrgicos estériles para procedimientos médicos y quirúrgicos.",
    brand: "3M",
    variant: "1003",
    subdesc: "",
    unit: "Caja x 10",
    price: 94.46,
  },
  {
    id: 17,
    title: "CAMPOS QUIRÚRGICOS STERI DRAPE",
    description:
      "Campos quirúrgicos estériles para procedimientos médicos y quirúrgicos.",
    brand: "3M",
    variant: "1019",
    subdesc: "180cm x 130cm",
    unit: "Caja x 10",
    price: 155.6,
  },
  {
    id: 17,
    title: "CAMPOS QUIRÚRGICOS STERI DRAPE",
    description:
      "Campos quirúrgicos estériles para procedimientos médicos y quirúrgicos.",
    brand: "3M",
    variant: "1016",
    subdesc: "",
    unit: "Caja x 10",
    price: 118.09,
  },
  {
    id: 18,
    title: "VENDAS ELÁSTICAS",
    description: "Venda elástica autoadherente e hipoalergénica.",
    brand: "3M",
    variant: "1582",
    subdesc: "5,08cm x 4,57cm",
    unit: "Caja x 36 rollos",
    price: 120.43,
  },
  {
    id: 18,
    title: "VENDAS ELÁSTICAS",
    description: "Venda elástica autoadherente e hipoalergénica.",
    brand: "3M",
    variant: "1583",
    subdesc: "7,62cm x 4,57cm",
    unit: "Caja x 24 rollos",
    price: 120.27,
  },
  {
    id: 18,
    title: "VENDAS ELÁSTICAS",
    description: "Venda elástica autoadherente e hipoalergénica.",
    brand: "3M",
    variant: "1584",
    subdesc: "10,16cm x 4,57cm",
    unit: "Caja x 18 rollos",
    price: 99.52,
  },
  {
    id: 19,
    title: "SUTURAS STERI STRIP",
    description:
      "Suturas cutáneas adhesivas reforzadas. Diseñadas de material microporoso no tejido y filamentos reforzados para una mayor resistencia. Adhesivo hipoalergénico sensible a la presión.",
    brand: "3M",
    variant: "R1540",
    subdesc: "3mm x 75mm",
    unit: "Caja x 50",
    price: 74.87,
  },
  {
    id: 19,
    title: "SUTURAS STERI STRIP",
    description:
      "Suturas cutáneas adhesivas reforzadas. Diseñadas de material microporoso no tejido y filamentos reforzados para una mayor resistencia. Adhesivo hipoalergénico sensible a la presión.",
    brand: "3M",
    variant: "R1541",
    subdesc: "6,3mm x 76mm",
    unit: "Caja x 50",
    price: 54.88,
  },
  {
    id: 19,
    title: "SUTURAS STERI STRIP",
    description:
      "Suturas cutáneas adhesivas reforzadas. Diseñadas de material microporoso no tejido y filamentos reforzados para una mayor resistencia. Adhesivo hipoalergénico sensible a la presión.",
    brand: "3M",
    variant: "R1546",
    subdesc: "6mm x 100mm",
    unit: "Caja x 50",
    price: 103.91,
  },
  {
    id: 19,
    title: "SUTURAS STERI STRIP",
    description:
      "Suturas cutáneas adhesivas reforzadas. Diseñadas de material microporoso no tejido y filamentos reforzados para una mayor resistencia. Adhesivo hipoalergénico sensible a la presión.",
    brand: "3M",
    variant: "R1547",
    subdesc: "12mm x 100mm",
    unit: "Caja x 50",
    price: 91.2,
  },
  {
    id: 19,
    title: "SUTURAS STERI STRIP",
    description:
      "Suturas cutáneas adhesivas reforzadas. Diseñadas de material microporoso no tejido y filamentos reforzados para una mayor resistencia. Adhesivo hipoalergénico sensible a la presión.",
    brand: "3M",
    variant: "R1548",
    subdesc: "25mm x 125mm",
    unit: "Caja x 25",
    price: 114.54,
  },
  {
    id: 20,
    title: "DÓSIS DE ÓXIDO DE ETILENO",
    description:
      "Cartucho de dosis única de óxido de etileno al 100%. Diseñados para proporcionar sistemas seguros que reducen la posibilidad de fugas y exposición al gas.",
    brand: "3M",
    variant: "4-100",
    subdesc: "Cartucho de 100gr",
    unit: "Caja x 12",
    price: 290.15,
  },
  {
    id: 20,
    title: "DÓSIS DE ÓXIDO DE ETILENO",
    description:
      "Cartucho de dosis única de óxido de etileno al 100%. Diseñados para proporcionar sistemas seguros que reducen la posibilidad de fugas y exposición al gas.",
    brand: "3M",
    variant: "8-170",
    subdesc: "Cartucho de 170gr",
    unit: "Caja x 12",
    price: 248.29,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1262",
    subdesc: "Vapor 48hs",
    unit: "Caja x 100",
    price: 193.25,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1264",
    subdesc: "ETO 48hs",
    unit: "Caja x 100",
    price: 217.65,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1292",
    subdesc: "Vapor 3hs",
    unit: "Caja x 50",
    price: 176.18,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1294",
    subdesc: "ETO 4hs",
    unit: "Caja x 50",
    price: 169.48,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1492V",
    subdesc: "Vapor 24min",
    unit: "Caja x 50",
    price: 215.32,
  },
  {
    id: 21,
    title: "INDICADORES BIOLÓGICOS ATTEST™",
    description:
      "Familia de Indicadores biológicos Attest™ para diferentes tipos de esterilización.",
    brand: "3M",
    variant: "1295",
    subdesc: "VH2O2 24min",
    unit: "Caja x 30",
    price: 417.84,
  },
  {
    id: 22,
    title: "INDICADOR QUIMICO ESTERILIZACION",
    description:
      "Familia de Indicadores químicos para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1243A",
    subdesc: "Integrador químico Vapor",
    unit: "Caja x 500",
    price: 84.5,
  },
  {
    id: 22,
    title: "INDICADOR QUIMICO ESTERILIZACION",
    description:
      "Familia de Indicadores químicos para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1243B",
    subdesc: "Integrador químico Vapor",
    unit: "Caja x 100",
    price: 36.95,
  },
  {
    id: 22,
    title: "INDICADOR QUIMICO ESTERILIZACION",
    description:
      "Familia de Indicadores químicos para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1348",
    subdesc: "Indicador químico VH₂O₂",
    unit: "Caja x 250",
    price: 72.41,
  },
  {
    id: 22,
    title: "INDICADOR QUIMICO ESTERILIZACION",
    description:
      "Familia de Indicadores químicos para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1251",
    subdesc: "Indicador químico ETO",
    unit: "Caja x 240",
    price: 29.07,
  },
  {
    id: 22,
    title: "INDICADOR QUIMICO ESTERILIZACION",
    description:
      "Familia de Indicadores químicos para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "VH2O2",
    subdesc: "VH₂O₂ 24min",
    unit: "Caja x 30",
    price: 417.84,
  },
  {
    id: 23,
    title: "TEST DE BOWIE-DICK",
    description:
      "Permite comprobar la evacuación correcta del aire de la cámara de esterilización y, en consecuencia, la total penetración del vapor en las cargas porosas (por ejemplo, bandanas o batas).",
    brand: "3M",
    variant: "00135",
    subdesc: "Paquete de prueba",
    unit: "Caja x 6",
    price: 52.46,
  },
  {
    id: 24,
    title: "CINTA INDICADORA",
    description:
      "Familia de cintas indicadoras químicas, sin plomo, para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1322-12",
    subdesc: "Vapor 12mm x 55m",
    unit: "Caja x 42",
    price: 266.29,
  },
  {
    id: 24,
    title: "CINTA INDICADORA",
    description:
      "Familia de cintas indicadoras químicas, sin plomo, para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1322-18",
    subdesc: "Vapor 18mm x 55m",
    unit: "Caja x 28",
    price: 252.2,
  },
  {
    id: 24,
    title: "CINTA INDICADORA",
    description:
      "Familia de cintas indicadoras químicas, sin plomo, para diferentes procedimientos de esterilización.",
    brand: "3M",
    variant: "1228",
    subdesc: "Peróxido de Hidrógeno 18mm x 55m",
    unit: "Caja x 24",
    price: 474.23,
  },
  {
    id: 25,
    title: "INCUBADORA",
    description: "Incubadoras para Indicadores biológicos.",
    brand: "3M",
    variant: "390",
    subdesc: "Vapor 3hs",
    unit: "Unidad",
    price: 1299.3,
  },
  {
    id: 25,
    title: "INCUBADORA",
    description: "Incubadoras para Indicadores biológicos.",
    brand: "3M",
    variant: "390G",
    subdesc: "ETO 4hs",
    unit: "Unidad",
    price: 1299.3,
  },
  {
    id: 25,
    title: "INCUBADORA",
    description: "Incubadoras para Indicadores biológicos.",
    brand: "3M",
    variant: "490",
    subdesc: "Vapor y VH₂O₂ 24min",
    unit: "Unidad",
    price: 1397.89,
  },
  {
    id: 25,
    title: "INCUBADORA",
    description: "Incubadoras para Indicadores biológicos.",
    brand: "3M",
    variant: "490M",
    subdesc: "Vapor y VH₂O₂ 24min",
    unit: "Unidad",
    price: 724.04,
  },
  {
    id: 26,
    title: "SISTEMA DE CALENTAMIENTO DE FLUIDOS",
    description:
      "El sistema de calentamiento de sangre y fluidos Ranger™ está diseñado para el calentamiento de fluidos de irrigación intravascular en aplicaciones como: Calentamiento de sangre, plasma, plaquetas y líquidos menos crioprecipitados.",
    brand: "3M",
    variant: "242",
    subdesc: "Set de flujo estándar",
    unit: "Caja x 10",
    price: 208.66,
  },
  {
    id: 26,
    title: "SISTEMA DE CALENTAMIENTO DE FLUIDOS",
    description:
      "El sistema de calentamiento de sangre y fluidos Ranger™ está diseñado para el calentamiento de fluidos de irrigación intravascular en aplicaciones como: Calentamiento de sangre, plasma, plaquetas y líquidos menos crioprecipitados.",
    brand: "3M",
    variant: "243",
    subdesc: "Set de alto flujo",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 26,
    title: "SISTEMA DE CALENTAMIENTO DE FLUIDOS",
    description:
      "El sistema de calentamiento de sangre y fluidos Ranger™ está diseñado para el calentamiento de fluidos de irrigación intravascular en aplicaciones como: Calentamiento de sangre, plasma, plaquetas y líquidos menos crioprecipitados.",
    brand: "3M",
    variant: "2245",
    subdesc: "Unidad de calentamiento",
    unit: "Unidad",
    price: null,
  },
  {
    id: 27,
    title: "Manta bajo paciente adulto",
    description: "Manta para uso en pacientes adultos.",
    brand: "3M",
    variant: "545",
    subdesc: "Manta bajo paciente adulto",
    unit: "Caja x 10",
    price: 160.65,
  },
  {
    id: 28,
    title: "Manta bajo paciente pediátrica",
    description: "Manta para uso en pacientes pediátricos.",
    brand: "3M",
    variant: "550",
    subdesc: "Manta bajo paciente pediátrica",
    unit: "Caja x 10",
    price: 201.34,
  },
  {
    id: 29,
    title: "Manta bajo paciente adulto, acceso completo",
    description: "Manta para uso en pacientes adultos, con acceso completo.",
    brand: "3M",
    variant: "635",
    subdesc: "Manta bajo paciente adulto, acceso completo",
    unit: "Caja x 5",
    price: 166.99,
  },
  {
    id: 30,
    title: "Manta bajo paciente neonata",
    description: "Manta para uso en pacientes neonatos.",
    brand: "3M",
    variant: "555",
    subdesc: "Manta bajo paciente neonata",
    unit: "Caja x 10",
    price: 154.76,
  },
  {
    id: 31,
    title: "Manta para parte inferior",
    description: "Manta para uso en la parte inferior del paciente.",
    brand: "3M",
    variant: "525",
    subdesc: "Manta para parte inferior",
    unit: "Caja x 10",
    price: 91.57,
  },
  {
    id: 32,
    title: "Manta sobre cuerpo completo adulto",
    description: "Manta para cubrir el cuerpo completo de un paciente adulto.",
    brand: "3M",
    variant: "300",
    subdesc: "Manta sobre cuerpo completo adulto",
    unit: "Caja x 10",
    price: 89.85,
  },
  {
    id: 33,
    title: "Manta sobre cuerpo completo adulto con acceso múltiple",
    description:
      "Manta para cubrir el cuerpo completo de un paciente adulto con acceso múltiple.",
    brand: "3M",
    variant: "315",
    subdesc: "Manta sobre cuerpo completo adulto con acceso múltiple",
    unit: "Caja x 10",
    price: 92.37,
  },
  {
    id: 34,
    title: "Manta multiposición",
    description: "Manta diseñada para múltiples posiciones del paciente.",
    brand: "3M",
    variant: "622",
    subdesc: "Manta multiposición",
    unit: "Caja x 10",
    price: 79.89,
  },
  {
    id: 35,
    title: "Unidad de calentamiento por sistema de aire forzado",
    description: "Equipo para calentamiento por sistema de aire forzado.",
    brand: "3M",
    variant: "775",
    subdesc: "Unidad de calentamiento por sistema de aire forzado",
    unit: "Unidad",
    price: 1855.65,
  },
  {
    id: 36,
    title: "Carro de transporte para unidad de calentamiento",
    description:
      "Carro diseñado para el transporte de unidades de calentamiento.",
    brand: "3M",
    variant: "90090",
    subdesc: "Carro de transporte para unidad de calentamiento",
    unit: "Unidad",
    price: 277.31,
  },
  {
    id: 37,
    title: "Placa para desfibrilador",
    description:
      "Almohadillas de gel conductor para usar en la desfibrilación.",
    brand: "3M",
    variant: "2346N",
    subdesc: "Placa para desfibrilador",
    unit: "Caja x 10",
    price: 85.21,
  },
  {
    id: 38,
    title: "Guantes Sempermed para cirugía estériles",
    description: "Guantes marca Sempermed. Calidad, comodidad y protección.",
    brand: "Sempermed",
    variant: "Classic",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma minimo 0,14 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 38,
    title: "Guantes Sempermed para cirugía estériles",
    description: "Guantes marca Sempermed. Calidad, comodidad y protección.",
    brand: "Sempermed",
    variant: "Derma Plus",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,19 - 0,24 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 38,
    title: "Guantes Sempermed para cirugía estériles",
    description: "Guantes marca Sempermed. Calidad, comodidad y protección.",
    brand: "Sempermed",
    variant: "Sempermed Supreme",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,19-0,23mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 38,
    title: "Guantes Sempermed para cirugía estériles",
    description: "Guantes marca Sempermed. Calidad, comodidad y protección.",
    brand: "Sempermed",
    variant: "Syntegra IR de Polisopreno",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,19 - 0,24 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 39,
    title: "Guantes Sempercare de latex para examinación",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Edition IC",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,12 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 40,
    title: "Guantes Sempercare de nitrilo",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Velvet",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,06 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 40,
    title: "Guantes Sempercare de nitrilo",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Skin2",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,07 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 40,
    title: "Guantes Sempercare de nitrilo",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Nitrile",
    subdesc:
      "Espesor de pared medido en una sola capa en el área de la palma 0,09 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 41,
    title: "Guantes Sempercare de nitrilo largos",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Safe+",
    subdesc: "Espesor de pared medido en una sola capa en el área de la palma 0,09 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 42,
    title: "Guantes Sempercare de vinilo para examinación",
    description: "Guantes marca Sempercare. Calidad, comodidad y protección.",
    brand: "Sempercare",
    variant: "Synstretech",
    subdesc: "Espesor de pared medido en una sola capa en el área de la palma 0,09 mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 43,
    title: "Guantes Supercare de latex para examinación",
    description: "Guantes marca Supercare. Calidad, comodidad y protección.",
    brand: "Supercare",
    variant: "Latex",
    subdesc: "Guantes de Latex con Polvo",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 43,
    title: "Guantes Supercare de latex para examinación",
    description: "Guantes marca Supercare. Calidad, comodidad y protección.",
    brand: "Supercare",
    variant: "Latex Powder Free",
    subdesc: "Guantes de Latex sin Polvo",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 44,
    title: "Guantes Supercare nitrilo",
    description: "Guantes marca Supercare. Calidad, comodidad y protección.",
    brand: "Supercare",
    variant: "Nitrilo",
    subdesc: "Guantes de Nitrilo Negros. Largo de los guantes: 230mm",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 45,
    title: "Guantes B-Guard estériles",
    description: "Guantes marca B-Guard.",
    brand: "B-Guard",
    variant: "Latex Powder",
    subdesc: "Guantes de Latex con Polvo",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 45,
    title: "Guantes B-Guard estériles",
    description: "Guantes marca B-Guard.",
    brand: "B-Guard",
    variant: "Latex Free",
    subdesc: "Guantes de Polisopreno sin Polvo",
    unit: "Caja x 10",
    price: null,
  },
  {
    id: 46,
    title: "Guantes B-Guard de nitrilo para examinación",
    description: "Guantes marca B-Guard.",
    brand: "B-Guard",
    variant: "Color Violeta",
    subdesc: "Guantes de Polisopreno sin Polvo",
    unit: "Caja x 10",
    price: null,
  },
    {
    id: 46,
    title: "Guantes B-Guard de nitrilo para examinación",
    description: "Guantes marca B-Guard.",
    brand: "B-Guard",
    variant: "Color Negro",
    subdesc: "Guantes de Polisopreno sin Polvo",
    unit: "Caja x 10",
    price: null,
  },
  // {
  //   id: 38,
  //   title: "Guantes Sempermed Latex",
  //   description: "Guates Sempermed de látex. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempermed",
  //   variant: "Supreme PF ML 7.5",
  //   subdesc: "3000006101 - Edición Supreme PF ML 7.5",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 38,
  //   title: "Guantes Sempermed Latex",
  //   description: "Guates Sempermed de látex. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempermed",
  //   variant: "Classic AQL 0,65 PP",
  //   subdesc: "3000013021 - Edición Classic AQL 0,65 PP",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 38,
  //   title: "Guantes Sempermed Latex",
  //   description: "Guates Sempermed de látex. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempermed",
  //   variant: "Syntegra IR PF 7.5",
  //   subdesc: "3000011685 - Edición Syntegra IR PF 7.5",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "IC NR PF NA",
  //   subdesc: "3000001787 - Edición IC NR PF NA",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "SHINE+ NBR PF WH",
  //   subdesc: "3000002090 - Edición SHINE+ NBR PF WH",
  //   unit: "Caja x 150",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "Velvet NBR PF CO",
  //   subdesc: "3000014665 - Edición Sempercare velvet NBR PF CO",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "SKIN2 NBR PF VB",
  //   subdesc: "3000002200 - Edición Sempercare SKIN2 NBR PF VB",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "SG STYLE POD NBR PF BK",
  //   subdesc: "3000010369 - Edición Semperguard SG STYLE POD NBR PF BK",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "Nitrile NBR PF OB",
  //   subdesc: "3000002119 - Edición Nitrile NBR PF OB",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "Safe+ NBR PF RB",
  //   subdesc: "3000003712 - Edición Safe+ NBR PF RB",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "Safe+ 1.0 NBR PF RB",
  //   subdesc: "3000015034 - Edición Safe+ 1.0 NBR PF RB",
  //   unit: "Caja x 100",
  //   price: null,
  // },
  // {
  //   id: 39,
  //   title: "Guantes Sempercare Nitrilo",
  //   description: "Guates Sempercare de Nitrilo. Calidad, comodidad y protección contra infecciones.",
  //   brand: "Sempercare",
  //   variant: "Synstretch PVC PF YW",
  //   subdesc: "3000002003 - Edición Synstretch PVC PF YW",
  //   unit: "Caja x 100",
  //   price: null,
  // },
].map((i) => {
  return {
    ...i,
    price: null,
  };
});

export default productos;
